### ISSUE TITLE
Version-update not committed (when changelog is not created due to being empty)

### ISSUE THREAD

**Issue by RonaldTreur** [TriPSs/conventional-changelog-action#101]
Hi there! First off, thanks a bunch for creating this awesome action! 👍 I appreciate the time and effort you put into this as it saves me a lot of time when setting up new projects.

I have just set up a brand new project and included the latest version of your action in my Github workflows. And now -unfortunately- I ran into an issue.

I noticed that my first PR did not generate a version-commit. Now this could be because no changelog was generated (as the PR consists out of chores exclusively), but that is not what I expected after reading the README for this repo.

Could this be a bug, or is this indeed intended? In the latter case I will create a PR to clarify this in the README. Just in case it is a bug, I will add my workflow and action output here:

The configuration:
```yml
name: Create Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version & Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          preset: 'angular'
          output-file: 'false'

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: true
```

And the output:
```
Run TriPSs/conventional-changelog-action@v3
Using "angular" preset
Using "chore(release): {version}" as commit message
Using "Conventional Changelog Action" as git user.name
Using "conventional.changelog.action@github.com" as git user.email
Using "5" release count
Using "./package.json" as version file
Using "version" as version path
Using "v" as tag prefix
Using "false" as output file
Using "" as config file
Skipping empty releases is "enabled"
Skipping the update of the version file is "disabled"
Pull to make sure we have the full git history
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/some/nice.git
/usr/bin/git rev-parse --is-shallow-repository
true
/usr/bin/git pull --unshallow --tags --ff-only
From https://github.com/some/nice
 * [new branch]      gh-pages   -> origin/gh-pages
Already up to date.
Recommended release type: patch
Because: There are 0 BREAKING CHANGES and 0 features
Files to bump: ./package.json
Bumping version to file "./package.json" with extension "json"
Bumped file "/home/runner/work/some/nice/package.json" from "0.0.1" to "0.0.2"
Changelog generated
## 0.0.2 (2021-01-28)




Generated changelog is empty and skip-on-empty has been activated so we skip this step
```

Any help is much appreciated. Please let me know if this needs additional clarification.
