### ISSUE TITLE
Determining current version from git skips newly pulled tags

### ISSUE THREAD

**Issue by luispollo** [TriPSs/conventional-changelog-action#102]
First of all, thanks a lot for the awesome tool!

I came across what looks like a bug when setting this up today. It looks like, even though new tags get pulled before determining the current version from git, the library is ignoring them. In this example, you can see that tags `v0.176.0` and `v0.177.0` were pulled, but the action calculated the changelog between `v0.175.0` (newest tag before the pull) and `v0.176.0` (which it bumped to): https://github.com/spinnaker/keel/runs/1818362589?check_suite_focus=true#step:6:64

Here's my setup:
```yaml
      - name: Prepare changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "false"
          skip-version-file: "true"
          skip-commit: "true"
```

Am I perhaps misconfiguring something? I've tried my best to find similar occurrences in previously closed issues and looked over the code, which looks OK to me, so not sure what could be causing this to happen.
