### ISSUE TITLE
Release Count and Format is wrong

### ISSUE THREAD

**Issue by stevie-** [TriPSs/conventional-changelog-action#12]
Hi, thanks for the Action.

we use it in our workflow. It updates CHANGELOG.md, package.json and creates a new tag. But the format of the Changelog is not what we expect. There is just **one** release in the changelog. 
Also different to the npm cli version, there is no git compare link to the previous tag.

Our workflow config:
```yaml
      - uses: actions/checkout@master
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v1.3.0
        with:
          github-token: ${{ secrets.github_token }}
          git-message: "chore(release): {version}"
          preset: "angular"
          tag-prefix: "v"
          output-file: "CHANGELOG.md"
          changelog-release-count: 10
```

currrent Changelog.md
```
$ cat CHANGELOG.md
## 0.0.6 (2020-04-16)


```

expected Changelog generated with CLI 
```
$ conventional-changelog -p angular -k ./package.json -r 10 -t v
## [0.0.6](https://github.com/REDACTED/compare/v0.0.5...v0.0.6) (2020-04-16)



## [0.0.5](https://github.com/REDACTED/compare/v0.0.4...v0.0.5) (2020-04-15)


### Bug Fixes

* **changelog:** rebuild changelog ([REDACTED](https://github.com/REDACTED/commit/REDACTED))
* **changelog:** use latest stable ([REDACTED](https://github.com/REDACTED/commit/REDACTED))



## [0.0.4](https://github.com/REDACTED/compare/v0.0.3...v0.0.4) (2020-04-15)


### Bug Fixes

* **git:** case-insensitive filesystem ([REDACTED](https://github.com/REDACTED/commit/REDACTED))



## [0.0.3](https://github.com/REDACTED/compare/v0.0.2...v0.0.3) (2020-04-15)


### Bug Fixes

* **pipeline:** only validate when code is correct ([REDACTED](https://github.com/REDACTED/commit/REDACTED))



## [0.0.2](https://github.com/REDACTED/compare/REDACTED...v0.0.2) (2020-04-15)


### Bug Fixes

* **pipeline:** fix module test ([REDACTED](https://github.com/REDACTED/commit/REDACTED))
* **pipeline:** fix typo in ref ([REDACTED](https://github.com/REDACTED/commit/REDACTED))
* **pipeline:** initial version setup ([REDACTED](https://github.com/REDACTED/commit/REDACTED))
* **pipeline:** wait for other jobs before releasing ([REDACTED](https://github.com/REDACTED/commit/REDACTED))
* **s3:** correct transition rule type ([REDACTED](https://github.com/REDACTED/commit/REDACTED))


### Features

* **pipeline:** release version on successfull tests if master branch ([REDACTED](https://github.com/REDACTED/commit/REDACTED))

```

**Comment by stevie-** [comment]
thanks for the new release, there is no change in the changelog output.

here is the log of the workflow run

```

Run TriPSs/conventional-changelog-action@v2.0.1
  with:
    github-token: ***
    git-message: chore(release): {version}
    preset: angular
    tag-prefix: v
    output-file: CHANGELOG.md
    release-count: 10
Using "angular" preset
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/REDACTED.git
/usr/bin/git checkout master
Recommended release type: patch
New version: 0.0.8
Your branch is up to date with 'origin/master'.
Already on 'master'
Push all changes
/usr/bin/git add .
/usr/bin/git commit -m chore(release): v0.0.8
[master 7e8476c] chore(release): v0.0.8
 2 files changed, 3 insertions(+), 3 deletions(-)
/usr/bin/git tag -a v0.0.8 -m v0.0.8
/usr/bin/git push origin master --follow-tags
To https://github.com/REDACTED.git
   REDACTED..REDACTED  master -> master
 * [new tag]         v0.0.8 -> v0.0.8
```

**Comment by TriPSs** [comment]
Could you try to run it like this
```
- name: Conventional Changelog Action
  uses: TriPSs/conventional-changelog-action@v2.0.1
  with:
    github-token: ${{ secrets.github_token }}
```

**Comment by stevie-** [comment]
```

    steps:
      - uses: actions/checkout@master
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v2.0.1
        with:
          github-token: ${{ secrets.github_token }}
          # git-message: "chore(release): {version}"
          # preset: "angular"
          # tag-prefix: "v"
          # output-file: "CHANGELOG.md"
          # release-count: 10
```
Still just one Changelog
