### ISSUE TITLE
Not geting bump in either package.json or package-lock.json

### ISSUE THREAD

**Issue by DianomiJH** [TriPSs/conventional-changelog-action#121]
I've been trying to get this to work and I'm probably missing something simple but i can't for the life of me figure it out.

This is my bump.yml

```
name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN  }}
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: ''
        output-file: 'CHANGELOG.md'
        version-file: 'package.json, package-lock.json'
```

And this is my log,

```|Run TriPSs/conventional-changelog-action@v3
Using "angular" preset
Using "chore(release): {version}" as commit message
Using "Conventional Changelog Action" as git user.name
Using "conventional.changelog.action@github.com" as git user.email
Using "5" release count
Using "package.json, package-lock.json" as version file
Using "version" as version path
Using "" as tag prefix
Using "CHANGELOG.md" as output file
Using "" as config file
Skipping empty releases is "enabled"
Skipping the update of the version file is "disabled"
Pull to make sure we have the full git history
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/BanJoeH/PANTRI.git
/usr/bin/git rev-parse --is-shallow-repository
true
/usr/bin/git pull --unshallow --tags --ff-only
From https://github.com/BanJoeH/PANTRI
 * [new branch]      gh-pages   -> origin/gh-pages
Already up to date.
Recommended release type: patch
Because: There are 0 BREAKING CHANGES and 0 features
Files to bump: package.json, package-lock.json
Bumping version to file "package.json" with extension "json"
Bumping version to file "package-lock.json" with extension "json"
Bumped file "/home/runner/work/PANTRI/PANTRI/package.json" from "2.1.0" to "2.1.1"
Bumped file "/home/runner/work/PANTRI/PANTRI/package-lock.json" from "2.1.0" to "2.1.1"
Changelog generated
## 2.1.1 (2021-08-20)




Generated changelog is empty and skip-on-empty has been activated so we skip this step
```

Anyhelp would be greatly apreciated
