### ISSUE TITLE
Do custom configs actually work?

### ISSUE THREAD

**Issue by adxmcollins** [TriPSs/conventional-changelog-action#123]
Hi there, I'm trying to use a custom config but the changelog will not generate for some reason. Do you have any insight?

If I understand correctly, setting the below config should mean that the changelog contains commits with the following messages that are not set to hidden.

config:
```
'use strict'
const config = require('conventional-changelog-conventionalcommits');

module.exports = config({
    "types": [
        { type: 'feat', section: 'Features' },
        { type: 'fix', section: 'Bug Fixes' },
        { type: 'perf', section: 'Performance' },
        { type: 'revert', section: 'Reverts' },
        { type: 'build', section: 'Build System' },
        { type: 'ci', section: 'Continuous Integration' },
        { type: 'refactor', section: 'Code Refactoring' },
        { type: 'chore', section: 'Chores' },
        { type: 'docs', section: 'Documentation' },
        { type: 'style', section: 'Styles' },
        { type: 'test', section: 'Tests' },
        { type: 'wip', section: 'WIP', hidden: true },
        { type: 'hide', section: 'Hidden', hidden: true },
        { type: 'release', section: 'Releases', hidden: true },
    ]
})
```

workflow:
```
- name: Changelog
  uses: TriPSs/conventional-changelog-action@v3
  with:
    github-token: ${{secrets.github_token}}
    git-message: 'chore(release): {version}'
    git-user-name: 'XXX'
    git-user-email: 'XXX'
    release-count: '0'
    config-file-path: ./changelog.config.js
```
Yet, in the action output, we get:

```
Using "" preset
Using "./changelog.config.js" as config file

...

Generated changelog is empty and skip-on-empty has been activated so we skip this step
```

Despite having the following dummy commits that I have setup:

```
@adxmcollins
chore: update presets

@adxmcollins
ci: update CI

@adxmcollins
build: update automatic build

@adxmcollins
chore: update
```

The changelog generates fine for `feat` and `fix` commits, so it seems like it is just ignoring the config I set and using the default one.

**Comment by TriPSs** [comment]
Hi, could you try by adding quotes to it? Like:

```
- name: Changelog
  uses: TriPSs/conventional-changelog-action@v3
  with:
    github-token: ${{secrets.github_token}}
    git-message: 'chore(release): {version}'
    git-user-name: 'XXX'
    git-user-email: 'XXX'
    release-count: '0'
    config-file-path: './changelog.config.js'
```

Also could you share the logs?
