### ISSUE TITLE
exclamation mark (!)  in commit message instead BREAKING CHANGE missbehavior

### ISSUE THREAD

**Issue by lukaszgoworko** [TriPSs/conventional-changelog-action#124]
# Exclamation mark causing wired behavior

## Our configuration 

this is our step in pipeline:
```yaml
        steps:
            -   uses: actions/checkout@v2
            -   name: Generate changelog and tag (without writing to file nor committing)
                id: changelog
                uses: TriPSs/conventional-changelog-action@v3
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    output-file: 'false'
                    skip-commit: 'true'
                    skip-on-empty: 'false'

            -   name: Create Release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ steps.changelog.outputs.tag }}
                    release_name: ${{ steps.changelog.outputs.tag }}
                    body: ${{ steps.changelog.outputs.clean_changelog }}
```

our commit message is containing an exclamation mark `!` and no `BREAKING CHANGE` in footer

```
    feat(attribute)!: add attribute-key for attribute references
    
    task #VILO-517
```

## Current Behavior

the action is not crating the change log (it is empty) and the next tag contains is a patch not a major bump

### Try to dig into the problem
we tried to add the `BREAKING CHANGE` into the footer:

```
    feat(attribute)!: add attribute-key for attribute references
    
    task #VILO-517
    BREAKING CHANGE: mandatory field added
```

this ends up with an correct bump to major version and we have a changelog, but the format looks like this:

---
---

## Features

- attribute: add attribute-key for attribute references (ca21dcc), closes #VILO-517

- feat!: remove entity property fk prefixes (3463fc5), closes #VILO-493

## BREAKING CHANGES

- attribute: mandatory field added

---
---

as you can see the `feat!: remove entity property fk prefixes (3463fc5), closes #VILO-493` contains the `feat!:` part

## Expectation

the [conventional commits doc](https://www.conventionalcommits.org/en/v1.0.0/) is giving this rule:

> If included in the type/scope prefix, breaking changes MUST be indicated by a ! immediately before the :. If ! is used, BREAKING  CHANGE: MAY be omitted from the footer section, and the commit description SHALL be used to describe the breaking change.

should  be ok as commit message
```
    feat(attribute)!: add attribute-key for attribute references
    
    task VILO-517
```
