### ISSUE TITLE
"Error: Could not find file" since latest release to v3.9.0

### ISSUE THREAD

**Issue by ICode4Hugs** [TriPSs/conventional-changelog-action#136]
Actions currently failing trying to download action repo:

```
Current runner version: '2.283.1'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
Download action repository 'TriPSs/conventional-changelog-action@v3' (SHA:a0379fa6213f99b1e8124dd16b34ebecedcbdf53)
Error: Could not find file '/home/runner/work/_actions/_temp_b9e81cee-d9fc-433a-bc04-9335872dd71c/_staging/TriPSs-conventional-changelog-action-a0379fa/node_modules/.bin/shjs'.
```

This is with a default boilerplate workflow:
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
```
