### ISSUE TITLE
Merge commits not added to changelog

### ISSUE THREAD

**Issue by pabpazjim** [TriPSs/conventional-changelog-action#147]
Merge commits are completely ignored by the changelog. While using this workflow:

```

name: Conventional Changelog
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@master

      # Version bump
      - name: Automated Version Bump
        id: versionBump
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: ""
          skip-on-empty: "false"
          skip-version-file: true
      - name: Automated GitHub Release
        uses: actions/create-release@v1
        if: ${{ steps.versionBump.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versionBump.outputs.tag }}
          release_name: ${{ steps.versionBump.outputs.tag }}
          body: ${{ steps.versionBump.outputs.clean_changelog }}
```

Let's say I create a doc-update branch from develop, make a set of commits and merge those into develop, with commit merge message being "docs: troubleshooting update \n <body>". Then, I merge develop into master with a commit message such as "feat: new version", or even with a non-conventional commit message. Changelog gets updated with a new version, but such version is empty, with no one of the merge commits showing.
