### ISSUE TITLE
Wrong version bumping while digit count increasing.

### ISSUE THREAD

**Issue by IATkachenko** [TriPSs/conventional-changelog-action#166]
From action point of view, after version `v0.10.0` we should use `v0.9.2` tag for next version:
```
...
 /usr/bin/git pull --unshallow --tags --ff-only
From https://github.com/IATkachenko/HA-YandexWeather
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.10.0    -> v0.10.0
 * [new tag]         v0.2.0     -> v0.2.0
 * [new tag]         v0.3.0     -> v0.3.0
 * [new tag]         v0.4.0     -> v0.4.0
 * [new tag]         v0.4.1     -> v0.4.1
 * [new tag]         v0.4.2     -> v0.4.2
 * [new tag]         v0.4.3     -> v0.4.3
 * [new tag]         v0.4.4     -> v0.4.4
 * [new tag]         v0.5.0     -> v0.5.0
 * [new tag]         v0.5.1     -> v0.5.1
 * [new tag]         v0.6.0     -> v0.6.0
 * [new tag]         v0.7.0     -> v0.7.0
 * [new tag]         v0.8.0     -> v0.8.0
 * [new tag]         v0.8.1     -> v0.8.1
 * [new tag]         v0.9.0     -> v0.9.0
 * [new tag]         v0.9.1     -> v0.9.1
Already up to date.
Recommended release type: patch
Because: There are 0 BREAKING CHANGES and 0 features
Using GIT to determine the new version
Changelog generated
## [0.9.2](https://github.com/IATkachenko/HA-YandexWeather/compare/v0.9.1...v0.9.2) (2022-07-02)
...
```
So, I have to remove all previous releases to release v0.10.1

Workflow config is:
```
jobs:
  changes:
    name: "Create changelog and tag"
    runs-on: ubuntu-latest
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        id: checkout

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          skip-version-file: "true"
          skip-commit: "true"
```
