### ISSUE TITLE
How to create a custom preset?

### ISSUE THREAD

**Issue by ghost** [TriPSs/conventional-changelog-action#176]
I've read the documentation thoroughly and understand that this action is based on presets like `angular` and `conventionalcommits`. However, I'm looking to create my own custom convention with custom `types` and would like to customize things like which `types` bump what version number and prevent bumping on breaking changes under `1.0.0`.

Is this possible? The closest thing I've found is `config-file-path` and the [Conventional Changelog Configuration Spec](https://github.com/conventional-changelog/conventional-changelog-config-spec/tree/master/versions/2.2.0#types) but I don't use `npm` and I'm not sure if this is the right way of going about this.

**Comment by TriPSs** [comment]
Maybe you can use the [config-file-path](https://github.com/TriPSs/conventional-changelog-action#config-file-path) option to define your own?

**Comment by ghost** [comment]
> Maybe you can use the [config-file-path](https://github.com/TriPSs/conventional-changelog-action#config-file-path) option to define your own?

I mentioned that but there is almost no explanation on how that works in the link you provided.

This is my current CD workflow:
```yaml
name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  first:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install conventional-changelog-conventionalcommits
          
      - name: Bump version, tag commit, and create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.14.1
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          git-message: 'release: {version}'
          version-file: pubspec.yaml
          skip-git-pull: true
          fallback-version: 0.0.1
          config-file-path: '.github/config/config.js'
```
and here is my config file:
```js
'use strict'
const config = require('conventional-changelog-conventionalcommits');

module.exports = config({
    "types": [
        { type: 'build', hidden: true },
        { type: 'release', hidden: true },
        { type: 'deprecate', section: 'Deprecated' }, // minor
        { type: 'devops', hidden: true },
        { type: 'docs', hidden: true },
        { type: 'feat', section: 'Added' }, // minor
        { type: 'fix', section: 'Fixed' }, // patch
        { type: 'perf', section: 'Performance' }, // patch
        { type: 'refactor', hidden: true },
        { type: 'remove', section: 'Removed' }, // major
        { type: 'security', section: 'Security' }, // patch
        { type: 'style', hidden: true},
        { type: 'test', hidden: true},
    ]
})
```

It works but everything not hidden bumps `patch` except `feat`. I'd like to customize it so certain types bump certain version numbers as the comments show above (e.g. `remove` bumps `major`).

I'd also like to follow the Dart convention below 1.0.0, which is:
> Although semantic versioning doesn’t promise any compatibility between versions prior to 1.0.0, the Dart community convention is to treat those versions semantically as well. The interpretation of each number is just shifted down one slot: going from 0.1.2 to 0.2.0 indicates a breaking change, going to 0.1.3 indicates a new feature, and going to 0.1.2+1 indicates a change that doesn’t affect the public API. For simplicity’s sake, avoid using + after the version reaches 1.0.0.

Do you know how to do this or if I'm going about this wrong?
