### ISSUE TITLE
Flagging as "pre-release" does not work, when fallback version is used

### ISSUE THREAD

**Issue by pdreker** [TriPSs/conventional-changelog-action#190]
When there is no version tag on the repo the action defaults to the fallback-version (0.1.0 by default). This version string is also used, when `pre-release: true` is set: the resulting version is 0.1.0.

Action, as used:
```yaml
      # Determine new Version from conventional commits
      - name: Conventional Changelog Action
        id: conv_cl
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-version-file: true
          pre-release: true
          pre-release-identifier: pre
          skip-commit: true
          skip-git-pull: true
          skip-on-empty: false
```

It could be argued, that the action does exactly as the documentation says (falling back to a pre-defined version string), if there is no previous version on the repo, but I would argue, that the behaviour is at least "surprising". I would have expected, that the pre-release is applied to the fallback version, i.e. the resulting version should be `0.1.0-pre.1`. When using trunk-based dev or similar, the very first release will often be a pre-release.
