### ISSUE TITLE
Question: can I have a new version without changelog?

### ISSUE THREAD

**Issue by RMCampos** [TriPSs/conventional-changelog-action#192]
I'm facing a situation where I want to be able to have a new version even when the changelog was not able to get any changes. I mean, from the log I can see a new version, but no descriptions, based on conventional commits. 

This is the job that I have:
```
- name: Conventional Changelog Update
  uses: TriPSs/conventional-changelog-action@v3
    id: changelog
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    output-file: 'CHANGELOG.md'
    skip-version-file: 'false'
    skip-commit: 'true'
    git-push: 'false'
```

And here's the log from the job:
```
Run TriPSs/conventional-changelog-action@v3
Using "angular" preset
Using "chore(release): {version} [skip ci]" as commit message
Using "Conventional Changelog Action" as git user.name
Using "conventional.changelog.action@github.com" as git user.email
Using "5" release count
Using "./package.json" as version file
Using "version" as version path
Using "v" as tag prefix
Using "CHANGELOG.md" as output file
Using "" as config file
Using "github.com" as gitUrl
Using "main" as gitBranch
Using "" as gitPath
Skipping empty releases is "enabled"
Skipping the update of the version file is "enabled"
Pull to make sure we have the full git history
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/bcgov/nr-spar-webapp.git
/usr/bin/git rev-parse --is-shallow-repository
false
/usr/bin/git pull --tags --ff-only
Already up to date.
Recommended release type: patch
Because: There are 0 BREAKING CHANGES and 0 features
Using GIT to determine the new version
Changelog generated
## [0.1.2](https://github.com/bcgov/nr-frontend-starting-app/compare/v0.1.1...v0.1.2) (2022-12-14)

Generated changelog is empty and skip-on-empty has been activated so we skip this step
```

My question is if I change the `skip-version-file` to `true` will do the trick? Thanks in advance.
