### ISSUE TITLE
Read old version from Cargo.toml

### ISSUE THREAD

**Issue by ChristophWurst** [TriPSs/conventional-changelog-action#195]
As noted in https://github.com/TriPSs/conventional-changelog-action/issues/194 I'm try to use this action for a Rust project. I found another issue.

```
      - name: Generate, commit and push changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.RELEASE_PAT }}
          skip-git-pull: "true"
          pre-commit: build/pre-commit.js
          release-count: 0
          version-file: Cargo.toml
          skip-version-file: true
```

^ my goal is to get the previous version out of Cargo.toml. That file looks like
``` 
[package]
name = "krankerl"
version = "0.14.0"
...
```

However, I get the warning:

> The version could not be detected, using fallback version '0.1.0'.

Full action output

```
 Using "angular" preset
Using "chore(release): {version} [skip ci]" as commit message
Using "Conventional Changelog Action" as git user.name
Using "conventional.changelog.action@github.com" as git user.email
Using "0" release count
Using "Cargo.toml" as version file
Using "version" as version path
Using "v" as tag prefix
Using "CHANGELOG.md" as output file
Using "" as config file
Using "github.com" as gitUrl
Using "master" as gitBranch
Using "" as gitPath
Using "build/pre-commit.js" as pre-commit script
Skipping empty releases is "enabled"
Skipping the update of the version file is "enabled"
Recommended release type: patch
Because: There are 0 BREAKING CHANGES and 0 features
Using GIT to determine the new version
The version could not be detected, using fallback version '0.1.0'.
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/ChristophWurst/krankerl.git
Changelog generated
# 0.1.0 (2022-12-20)




Generated changelog is empty and skip-on-empty has been activated so we skip this step
```
