### ISSUE TITLE
Question: Conventional changelog and manual tagging for releases possible?

### ISSUE THREAD

**Issue by marchingon12** [TriPSs/conventional-changelog-action#200]
I'm making an Android app and would like to add an automation, in which it automatically generates a version changelog and add itself to the `CHANGELOG.md` every time a new bunch of commits/PR is merged into the master repo. **If** a commit is pushed with a new version tag `v*` higher than the previous tag is pushed to the master repo, then the CHANGELOG should update as well, include the changelog starting from the previous release version till the current new version published to the release.

- **Question**: 
How do I configure the action to generate a conventional changelog and bump the tag every single time only when a release is intiated?

- **Problem**: 
I've been trying for multiple days to make the action work so that a changelog will be generated, stored in the output so that I can put it in release notes using another action in the same .yml config. However, the logs in job actions always say that either changelog is empty or tags are wrongly set.

My current config for the conv. changelog action:

```yaml
name: Releases
on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: ["master"]

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          clean: "true"
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-git-pull: "true"
          skip-tag: "true"
```

**Comment by jeacott1** [comment]
fwiw I had no luck with on:push:tags:- "v*"
and instead went with
```
on:
  create:

jobs:
  cmy_job:
    if: (contains(github.ref, '/tags/v'))
    ...
```

this works fine for me, but then I found that I couldnt control the to/from tag/commit range with this action so am looking at alts now.
