### ISSUE TITLE
how can I add a multiline commit message?

### ISSUE THREAD

**Issue by jeacott1** [TriPSs/conventional-changelog-action#206]
Hi,
 I would like to create a commit with a multiline message (eg fix: xxx \n refs: abc-def)
but when I try this, the \n is escaped and written literally. is there a workaround?

**Comment by TriPSs** [comment]
You could try something like:

```yaml
  git-message: |
    chore: Release
  
    Second line
```
