### ISSUE TITLE
`pre-release` options stops major version bump

### ISSUE THREAD

**Issue by abrondijk** [TriPSs/conventional-changelog-action#207]
When the option `pre-release` is set to true, it seems to be ignoring breaking changes.
My commit message was as following:
```
feat!: Test breaking change
```
The expected behaviour would be that the exclamation mark triggers a breaking change and thus a major version bump.
This was managed with the suggested solution in [#231](https://github.com/semantic-release/commit-analyzer/issues/231).

I have two actions using this action, a releaser and a pre-releaser. 

### Configuration

Releaser:
```yaml
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Version number
        id: version
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          preset: 'conventionalcommits'
          skip-on-empty: 'false'
          git-push: 'false'
          skip-git-pull: 'true'
          version-file: 'version.json'
```
Pre-releaser:
```yaml
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Version number
        id: version
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          preset: 'conventionalcommits'
          skip-on-empty: 'false'
          git-push: 'false'
          skip-git-pull: 'true'
          version-file: 'version.json'
          pre-release: 'true'
```
### Logs
Pre-eleaser (was run first):
```
Using "conventionalcommits" preset
Using "chore(release): {version} [skip ci]" as commit message
Using "Conventional Changelog Action" as git user.name
Using "conventional.changelog.action@github.com" as git user.email
Using "5" release count
Using "version.json" as version file
Using "version" as version path
Using "v" as tag prefix
Using "false" as output file
Using "" as config file
Using "github.com" as gitUrl
Using "main" as gitBranch
Using "" as gitPath
Skipping empty releases is "disabled"
Skipping the update of the version file is "disabled"
Pull to make sure we have the full git history
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/abrondijk/VisualGDB-Test.git
/usr/bin/git rev-parse --is-shallow-repository
true
/usr/bin/git pull --unshallow --tags --ff-only
From https://github.com/abrondijk/VisualGDB-Test
 * [new branch]      cpp                  -> origin/cpp
 * [new branch]      fourth-test          -> origin/fourth-test
 * [new branch]      revert-2-second-test -> origin/revert-2-second-test
 * [new branch]      second-test          -> origin/second-test
 * [new branch]      third-test           -> origin/third-test
 * [new tag]         v0.1.0               -> v0.1.0
 * [new tag]         v0.1.1               -> v0.1.1
 * [new tag]         v0.1.2               -> v0.1.2
 * [new tag]         v0.1.3               -> v0.1.3
 * [new tag]         v0.1.4               -> v0.1.4
 * [new tag]         v0.1.5               -> v0.1.5
 * [new tag]         v0.1.6               -> v0.1.6
 * [new tag]         v0.10.0              -> v0.10.0
 * [new tag]         v0.10.1              -> v0.10.1
 * [new tag]         v0.10.2              -> v0.10.2
 * [new tag]         v0.10.3              -> v0.10.3
 * [new tag]         v0.10.3-rc.0         -> v0.10.3-rc.0
 * [new tag]         v0.2.0               -> v0.2.0
 * [new tag]         v0.3.0               -> v0.3.0
 * [new tag]         v0.4.0               -> v0.4.0
 * [new tag]         v0.4.1               -> v0.4.1
 * [new tag]         v0.5.0               -> v0.5.0
 * [new tag]         v0.6.0               -> v0.6.0
 * [new tag]         v0.7.0               -> v0.7.0
 * [new tag]         v0.8.0               -> v0.8.0
 * [new tag]         v0.8.1               -> v0.8.1
 * [new tag]         v0.8.2               -> v0.8.2
 * [new tag]         v0.9.0               -> v0.9.0
 * [new tag]         v0.9.1               -> v0.9.1
Already up to date.
Recommended release type: major
Because: There is 1 BREAKING CHANGE and 0 features
Files to bump: version.json
Bumping version to file "version.json" with extension "json"
Bumped file "/home/runner/work/VisualGDB-Test/VisualGDB-Test/version.json" from "0.10.3" to "0.10.4-rc.0"
Changelog generated
### [0.10.4-rc.0](https://github.com/abrondijk/VisualGDB-Test/compare/v0.10.3...v0.10.4-rc.0) (2023-03-28)


### ⚠ BREAKING CHANGES

* Test breaking change

### Features

* Test breaking change ([f31ca69](https://github.com/abrondijk/VisualGDB-Test/commit/f31ca69943075f77a4bf66f7484ec79136e4e69c))


### Bug Fixes

* Test fix ([a85310c](https://github.com/abrondijk/VisualGDB-Test/commit/a85310cdac8b82cbe7b2185171253999ffd061ac))


New version: 0.10.4-rc.0
/usr/bin/git add .
/usr/bin/git commit -m chore(release): v0.10.4-rc.0 [skip ci]
[main 21b09da] chore(release): v0.10.4-rc.0 [skip ci]
 1 file changed, 1 insertion(+), 1 deletion(-)
/usr/bin/git tag -a v0.10.4-rc.0 -m v0.10.4-rc.0
Push all changes
/usr/bin/git push origin main --follow-tags
To https://github.com/abrondijk/VisualGDB-Test.git
   cc4a665..21b09da  main -> main
 * [new tag]         v0.10.4-rc.0 -> v0.10.4-rc.0
 ```
Releaser:
```
Using "conventionalcommits" preset
Using "chore(release): {version} [skip ci]" as commit message
Using "Conventional Changelog Action" as git user.name
Using "conventional.changelog.action@github.com" as git user.email
Using "5" release count
Using "version.json" as version file
Using "version" as version path
Using "v" as tag prefix
Using "false" as output file
Using "" as config file
Using "github.com" as gitUrl
Using "main" as gitBranch
Using "" as gitPath
Skipping empty releases is "disabled"
Skipping the update of the version file is "disabled"
Pull to make sure we have the full git history
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/abrondijk/VisualGDB-Test.git
/usr/bin/git rev-parse --is-shallow-repository
true
/usr/bin/git pull --unshallow --tags --ff-only
From https://github.com/abrondijk/VisualGDB-Test
 * [new branch]      cpp                  -> origin/cpp
 * [new branch]      fourth-test          -> origin/fourth-test
 * [new branch]      revert-2-second-test -> origin/revert-2-second-test
 * [new branch]      second-test          -> origin/second-test
 * [new branch]      third-test           -> origin/third-test
 * [new tag]         v0.1.0               -> v0.1.0
 * [new tag]         v0.1.1               -> v0.1.1
 * [new tag]         v0.1.2               -> v0.1.2
 * [new tag]         v0.1.3               -> v0.1.3
 * [new tag]         v0.1.4               -> v0.1.4
 * [new tag]         v0.1.5               -> v0.1.5
 * [new tag]         v0.1.6               -> v0.1.6
 * [new tag]         v0.10.0              -> v0.10.0
 * [new tag]         v0.10.1              -> v0.10.1
 * [new tag]         v0.10.2              -> v0.10.2
 * [new tag]         v0.10.3              -> v0.10.3
 * [new tag]         v0.10.3-rc.0         -> v0.10.3-rc.0
 * [new tag]         v0.10.4-rc.0         -> v0.10.4-rc.0
 * [new tag]         v0.2.0               -> v0.2.0
 * [new tag]         v0.3.0               -> v0.3.0
 * [new tag]         v0.4.0               -> v0.4.0
 * [new tag]         v0.4.1               -> v0.4.1
 * [new tag]         v0.5.0               -> v0.5.0
 * [new tag]         v0.6.0               -> v0.6.0
 * [new tag]         v0.7.0               -> v0.7.0
 * [new tag]         v0.8.0               -> v0.8.0
 * [new tag]         v0.8.1               -> v0.8.1
 * [new tag]         v0.8.2               -> v0.8.2
 * [new tag]         v0.9.0               -> v0.9.0
 * [new tag]         v0.9.1               -> v0.9.1
Already up to date.
Recommended release type: major
Because: There is 1 BREAKING CHANGE and 0 features
Files to bump: version.json
Bumping version to file "version.json" with extension "json"
Bumped file "/home/runner/work/VisualGDB-Test/VisualGDB-Test/version.json" from "0.10.4-rc.0" to "1.0.0"
Changelog generated
## [1.0.0](https://github.com/abrondijk/VisualGDB-Test/compare/v0.10.3...v1.0.0) (2023-03-28)

### 0.10.4-rc.0 (2023-03-28)


### ⚠ BREAKING CHANGES

* Test breaking change

### Features

* Test breaking change ([f31ca69](https://github.com/abrondijk/VisualGDB-Test/commit/f31ca69943075f77a4bf66f7484ec79136e4e69c))


### Bug Fixes

* Test fix ([a85310c](https://github.com/abrondijk/VisualGDB-Test/commit/a85310cdac8b82cbe7b2185171253999ffd061ac))


New version: 1.0.0
/usr/bin/git add .
/usr/bin/git commit -m chore(release): v1.0.0 [skip ci]
[main 840b383] chore(release): v1.0.0 [skip ci]
 1 file changed, 1 insertion(+), 1 deletion(-)
/usr/bin/git tag -a v1.0.0 -m v1.0.0
Push all changes
/usr/bin/git push origin main --follow-tags
To https://github.com/abrondijk/VisualGDB-Test.git
   21b09da..840b383  main -> main
 * [new tag]         v1.0.0 -> v1.0.0
```

As the logs of the pre-releaser suggest, the exclamation mark does trigger a major version increase, but it uses a patch increase anyway:
```
Recommended release type: major
Because: There is 1 BREAKING CHANGE and 0 features
Files to bump: version.json
Bumping version to file "version.json" with extension "json"
Bumped file "/home/runner/work/VisualGDB-Test/VisualGDB-Test/version.json" from "0.10.3" to "0.10.4-rc.0"
```
Whereas the releaser prints basically the same logs but does actually bumps the major version.
What gives?
