### ISSUE TITLE
feat!: syntax does not work

### ISSUE THREAD

**Issue by BernhardBaumrock** [TriPSs/conventional-changelog-action#217]
Please have a look at this repo: https://github.com/baumrock/conventionalcommits/commits/main

<img width="676" alt="image" src="https://github.com/TriPSs/conventional-changelog-action/assets/8488586/954a9ef1-1832-4c45-9045-2e1c43a02230">

Am I doing anything wrong?

Any help would be greatly appreciated! Thx in advance

**Comment by TriPSs** [comment]
This is because `feat!` is not considered breaking change in the angular preset I think, only in the conventional commit preset

**Comment by BernhardBaumrock** [comment]
Thx @TriPSs for the quick reply! So how can I make it use the syntax listed in https://www.conventionalcommits.org/en/v1.0.0/ ? I thought I'm already using that...

**Comment by TriPSs** [comment]
By changeing the `preset` option:
> Optional preset: Preset that is used from conventional commits. Default angular.


```yml
- name: Conventional Changelog Action
  uses: TriPSs/conventional-changelog-action@v3
  with:
    preset: 'angular' <- here, note: you will have to make sure that the other preset is installed in your repo.
```

**Comment by BernhardBaumrock** [comment]
I'm sorry but I'm lost @TriPSs 
I understand that I need to change the preset, but the question is which value do I have to use? I've searched the repo for "preset" but I could not find any helpful information and also try and error with using `conventionalcommits` did not work.
Also where can I find more information about `other preset is installed on your system`?

**Comment by TriPSs** [comment]
You can find the different presets [here](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages) and the value to use is described inside the README of the corresponding preset.

You need to make sure it's installed with `npm install <conventional-changelog-conventionalcommits>`, check [here](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits#direct-usage-as-a-base-preset-so-you-can-customize-it)

**Comment by BernhardBaumrock** [comment]
Thx @TriPSs that's a pity. I'll stick with the angular preset then as it's easier to use a slightly different syntax than having to npm install external dependencies on every project where I'm using it.
Thx for your help!

**Comment by TriPSs** [comment]
@BernhardBaumrock FYI: Since `v5` we now compile presets inside the action and since `v5.1.0` the `conventionalcommits` is also added.

**Comment by BernhardBaumrock** [comment]
hey @TriPSs thx for the heads up! Awesome! Just tested and this works for me:

```
name: Releases
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.1.0
        with:
          preset: "conventionalcommits"
          github-token: ${{ secrets.github_token }}

      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
```
