### ISSUE TITLE
Retaining prior manually generated logs

### ISSUE THREAD

**Issue by binomialstew** [TriPSs/conventional-changelog-action#219]
Is there any way to retain prior manually generated logs that exist in `CHANGELOG.md` at the time of generation while still adding new release changelogs to the same file?

I have some manually generated changelogs of changes to the project prior to using this action, but when I run this on push to that branch, the existing logs are overwritten with only the latest version existing in the logs after the action runs. Subsequent runs of the action add to this file--keeping the logs generated by this action as expected. I have added tags and versions that match the versions in the changelog, and the action is incrementing that version correctly, but it replaces any preexisting content within `CHANGELOG.md`.

Can I keep the preexisting content of `CHANGELOG.md` intact while using this action somehow?

My action config:
```yaml
- name: Generate Changelogs
        uses: TriPSs/conventional-changelog-action@v3
        with:
          config-file-path: "./packages/[package-name]/config/conventional-changelog.js"
          git-path: "./packages[package-name]/"
          github-token: "${{ secrets.BUILD_TOKEN }}"
          tag-prefix: [package-name]@v
          version-file: "./packages/[package-name]/package.json"
          output-file: "./packages/[package-name]/CHANGELOG.md"
          release-count: 0
```
