### ISSUE TITLE
Preset option with "conventionalcommits" doesn't seem to work 

### ISSUE THREAD

**Issue by JellyBellyDev** [TriPSs/conventional-changelog-action#246]
My config:
```yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          preset: conventionalcommits
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: ${{ github.actor }}
          git-user-email: ${{ github.actor }}@users.noreply.github.com
          tag-prefix: 'v'
```
and in action log i see:
```
Error: Error: Unable to load the "conventionalcommits" preset. Please make sure it's installed.
```
The possible values are not these: https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog/README.md#preset ?

Thanks
