### ISSUE TITLE
The process '/usr/bin/git' failed with exit code 1

### ISSUE THREAD

**Issue by magextensions** [TriPSs/conventional-changelog-action#248]
We get the following error:

`* [new branch]      issue/test-change-log -> origin/issue/test-change-log
 * [new branch]      master                -> origin/master
 * [new branch]      test431               -> origin/test431
 * [new tag]         v1.0.10               -> v1.0.10
 * [new tag]         v1.0.11               -> v1.0.11
 * [new tag]         v1.0.12               -> v1.0.12
 * [new tag]         v1.0.13               -> v1.0.13
 * [new tag]         v1.0.14               -> v1.0.14
 * [new tag]         v1.0.15               -> v1.0.15
 * [new tag]         v1.0.16               -> v1.0.16
 * [new tag]         v1.0.17               -> v1.0.17
 * [new tag]         v1.0.18               -> v1.0.18
 * [new tag]         v1.0.19               -> v1.0.19
 * [new tag]         v1.0.20               -> v1.0.20
 * [new tag]         v1.0.21               -> v1.0.21
 * [new tag]         v1.0.22               -> v1.0.22
 * [new tag]         v1.0.23               -> v1.0.23
 * [new tag]         v1.0.24               -> v1.0.24
 * [new tag]         v1.0.25               -> v1.0.25
 * [new tag]         v1.0.26               -> v1.0.26
 * [new tag]         v1.0.27               -> v1.0.27
 * [new tag]         v1.0.28               -> v1.0.28
 * [new tag]         v1.0.29               -> v1.0.29
 * [new tag]         v1.0.30               -> v1.0.30
 * [new tag]         v1.0.31               -> v1.0.31
 * [new tag]         v1.0.33               -> v1.0.33
 * [new tag]         v1.0.34               -> v1.0.34
 ! [rejected]        v1.0.35               -> v1.0.35  (would clobber existing tag)
 * [new tag]         v1.0.8                -> v1.0.8
 * [new tag]         v1.0.9                -> v1.0.9
Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 1
Error: Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (node:events:[51](https://github.com/start-mage/RestrictProductDelete/actions/runs/7495249411/job/20404929265#step:3:52)3:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:[57](https://github.com/start-mage/RestrictProductDelete/actions/runs/7495249411/job/20404929265#step:3:58)5:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:4[69](https://github.com/start-mage/RestrictProductDelete/actions/runs/7495249411/job/20404929265#step:3:70):27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`

Any idea what is going wrong?

**Comment by TriPSs** [comment]
Correct that you use v3? Try updating to the latest one (v5)

**Comment by magextensions** [comment]
Thanks for your fast reply!

Yes correct we used v3 and now testing with v5 we get the same

2024-01-11T22:33:04.5336592Z  * [new branch]      issue/test-change-log -> origin/issue/test-change-log
2024-01-11T22:33:04.5337616Z  * [new branch]      master                -> origin/master
2024-01-11T22:33:04.5338533Z  * [new branch]      test431               -> origin/test431
2024-01-11T22:33:04.5339525Z  * [new tag]         v1.0.10               -> v1.0.10
2024-01-11T22:33:04.5340802Z  * [new tag]         v1.0.11               -> v1.0.11
2024-01-11T22:33:04.5341436Z  * [new tag]         v1.0.12               -> v1.0.12
2024-01-11T22:33:04.5342056Z  * [new tag]         v1.0.13               -> v1.0.13
2024-01-11T22:33:04.5342613Z  * [new tag]         v1.0.14               -> v1.0.14
2024-01-11T22:33:04.5346704Z  * [new tag]         v1.0.15               -> v1.0.15
2024-01-11T22:33:04.5347594Z  * [new tag]         v1.0.16               -> v1.0.16
2024-01-11T22:33:04.5348180Z  * [new tag]         v1.0.17               -> v1.0.17
2024-01-11T22:33:04.5348933Z  * [new tag]         v1.0.18               -> v1.0.18
2024-01-11T22:33:04.5349498Z  * [new tag]         v1.0.19               -> v1.0.19
2024-01-11T22:33:04.5350078Z  * [new tag]         v1.0.20               -> v1.0.20
2024-01-11T22:33:04.5350625Z  * [new tag]         v1.0.21               -> v1.0.21
2024-01-11T22:33:04.5351166Z  * [new tag]         v1.0.22               -> v1.0.22
2024-01-11T22:33:04.5351705Z  * [new tag]         v1.0.23               -> v1.0.23
2024-01-11T22:33:04.5352247Z  * [new tag]         v1.0.24               -> v1.0.24
2024-01-11T22:33:04.5352783Z  * [new tag]         v1.0.25               -> v1.0.25
2024-01-11T22:33:04.5353325Z  * [new tag]         v1.0.26               -> v1.0.26
2024-01-11T22:33:04.5353861Z  * [new tag]         v1.0.27               -> v1.0.27
2024-01-11T22:33:04.5354400Z  * [new tag]         v1.0.28               -> v1.0.28
2024-01-11T22:33:04.5355106Z  * [new tag]         v1.0.29               -> v1.0.29
2024-01-11T22:33:04.5362157Z  * [new tag]         v1.0.30               -> v1.0.30
2024-01-11T22:33:04.5362744Z  * [new tag]         v1.0.31               -> v1.0.31
2024-01-11T22:33:04.5363297Z  * [new tag]         v1.0.33               -> v1.0.33
2024-01-11T22:33:04.5363852Z  * [new tag]         v1.0.34               -> v1.0.34
2024-01-11T22:33:04.5364578Z  ! [rejected]        v1.0.35               -> v1.0.35  (would clobber existing tag)
2024-01-11T22:33:04.5365285Z  * [new tag]         v1.0.8                -> v1.0.8
2024-01-11T22:33:04.5365847Z  * [new tag]         v1.0.9                -> v1.0.9
2024-01-11T22:33:04.5456424Z Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 1
2024-01-11T22:33:04.5458040Z     at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1702:25)
2024-01-11T22:33:04.5459781Z     at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1685:18)
2024-01-11T22:33:04.5461534Z     at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1579:27)
2024-01-11T22:33:04.5462678Z     at ChildProcess.emit (node:events:514:28)
2024-01-11T22:33:04.5463406Z     at maybeClose (node:internal/child_process:1105:16)
2024-01-11T22:33:04.5464229Z     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2024-01-11T22:33:04.5516542Z ##[error]Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1702:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1579:27)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2024-01-11T22:33:04.5764355Z Post job cleanup.
2024-01-11T22:33:04.7115622Z [command]/usr/bin/git version
2024-01-11T22:33:04.7166329Z git version 2.43.0
2024-01-11T22:33:04.7215485Z Temporarily overriding HOME='/home/runner/work/_temp/55ea7d24-7f31-488e-b24b-38495222b382' before making global git config changes
2024-01-11T22:33:04.7217005Z Adding repository directory to the temporary git global config as a safe directory
2024-01-11T22:33:04.7220309Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/##/##
2024-01-11T22:33:04.7262704Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-01-11T22:33:04.7302529Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-01-11T22:33:04.7549684Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-01-11T22:33:04.7578554Z http.https://github.com/.extraheader
2024-01-11T22:33:04.7592291Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-01-11T22:33:04.7630261Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-01-11T22:33:04.8155105Z Cleaning up orphan processes

**Comment by TriPSs** [comment]
Could you share your workflow?

**Comment by magextensions** [comment]
Yes sure!

```yml
on:
  create:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # # Push events to every tag not containing /

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          skip-version-file: 'true'
          release-count: '0'
          skip-tag: 'true'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          #tag_name: ${{ steps.changelog.outputs.tag }}
          #release_name: Release ${{ github.ref }}
          release_name: ${{ steps.changelog.outputs.tag }}
          #body: |
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
```

**Comment by TriPSs** [comment]
It could be related to the checkout, could you update that one the latest version `uses: actions/checkout@v4` and give it an other try?

**Comment by TriPSs** [comment]
Also small note: you can't use `skip-tag` and `skip-version-file` because the action would than be unable to determine the previous version.

**Comment by magextensions** [comment]
With `uses: actions/checkout@v4` we get the same error.

**Comment by magextensions** [comment]
> Also small note: you can't use `skip-tag` and `skip-version-file` because the action would than be unable to determine the previous version.

Thanks! we remove this

**Comment by TriPSs** [comment]
Could you run in debug mode and drop here the raw logs.

**Comment by magextensions** [comment]
Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1702:25)
 * [new branch]      issue/test-change-log -> origin/issue/test-change-log
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1685:18)
 * [new branch]      master                -> origin/master
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1579:27)
 * [new branch]      test431               -> origin/test431
    at ChildProcess.emit (node:events:[51](https://github.com/start-mage/RestrictProductDelete/actions/runs/7495426076/job/20405475877#step:3:52)4:28)
 * [new tag]         v1.0.10               -> v1.0.10
 * [new tag]         v1.0.11               -> v1.0.11
 * [new tag]         v1.0.12               -> v1.0.12
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
 * [new tag]         v1.0.13               -> v1.0.13
 * [new tag]         v1.0.14               -> v1.0.14
 * [new tag]         v1.0.15               -> v1.0.15
 * [new tag]         v1.0.16               -> v1.0.16
 * [new tag]         v1.0.17               -> v1.0.17
 * [new tag]         v1.0.18               -> v1.0.18
 * [new tag]         v1.0.19               -> v1.0.19
 * [new tag]         v1.0.20               -> v1.0.20
 * [new tag]         v1.0.21               -> v1.0.21
 * [new tag]         v1.0.22               -> v1.0.22
 * [new tag]         v1.0.23               -> v1.0.23
 * [new tag]         v1.0.24               -> v1.0.24
 * [new tag]         v1.0.25               -> v1.0.25
 * [new tag]         v1.0.26               -> v1.0.26
 * [new tag]         v1.0.27               -> v1.0.27
 * [new tag]         v1.0.28               -> v1.0.28
 * [new tag]         v1.0.29               -> v1.0.29
 * [new tag]         v1.0.30               -> v1.0.30
 * [new tag]         v1.0.31               -> v1.0.31
 * [new tag]         v1.0.33               -> v1.0.33
 * [new tag]         v1.0.34               -> v1.0.34
 ! [rejected]        v1.0.35               -> v1.0.35  (would clobber existing tag)
 * [new tag]         v1.0.8                -> v1.0.8
 * [new tag]         v1.0.9                -> v1.0.9
Error: Unhandled Rejection occurred. Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1702:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v5/dist/index.js:1579:27)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

**Comment by TriPSs** [comment]
`! [rejected] v1.0.35 -> v1.0.35 (would clobber existing tag)` I have the feeling it has to do with this line. If you could dump the raw logs with debug mode maybe we can see a bit more.

**Comment by TriPSs** [comment]
Wait, this is run on every tag creation? Usually this action would create the tag/bump the version so there is a possibility that the there is a tag created and this actions tries to bump to the same one causing the error.

**Comment by magextensions** [comment]
> Wait, this is run on every tag creation? Usually this action would create the tag/bump the version so there is a possibility that the there is a tag created and this actions tries to bump to the same one causing the error.

Yes true, sorry i forget to mention this

first we create the tag and after we run this one

**Comment by magextensions** [comment]
How we can fix this then? we can let the action create the tag as well?

**Comment by TriPSs** [comment]
You could use this action on the place where you create the tag, and use the action to create it.  If you only want a tag and no commit/file bumped that would look like this:

```yml
- name: Conventional Changelog Action
  uses: TriPSs/conventional-changelog-action@v3
  with:
    github-token: ${{ secrets.github_token }}
    skip-commit: "true"
    output-file: "false"

# If you also want it to be a GitHub release
- name: Create Release
  uses: actions/create-release@v1
  if: ${{ steps.changelog.outputs.skipped == 'false' }}
  env:
    GITHUB_TOKEN: ${{ secrets.github_token }}
  with:
    tag_name: ${{ steps.changelog.outputs.tag }}
    release_name: ${{ steps.changelog.outputs.tag }}
    body: ${{ steps.changelog.outputs.clean_changelog }}
```
