### ISSUE TITLE
Missing types in Release

### ISSUE THREAD

**Issue by rgb000** [TriPSs/conventional-changelog-action#254]
Hello.
We are facing with one strange behavior when generating GitHub Release. In Release we can see only features and bug fixes, but such types like `ci`, `chore`, `build` is not generated/present in Changelog and Release. 
GitHub action workflow: 
```
name: Releases
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release Action
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
```

Git log:
```
4c97fbc (tag: v1.2.0) chore(release): v1.2.0 [skip ci]
54069ef Merge pull request #20 from rgb000/feature/ip
83deb8c feat(ip): updated module outputs
b18eb82 feat: add ip module
97f3843 Merge pull request #19 from rgb000/feature/ci-update
5ed7a2e chore: updated pre-commit hooks
f3a70df chore: updated .gitignore
```

GitHub Release:
![image](https://github.com/TriPSs/conventional-changelog-action/assets/2604986/6b6ae46c-eff9-41e2-bcc9-64835e7e11a9)
