### ISSUE TITLE
Force push

### ISSUE THREAD

**Issue by Simranpal-Bainee** [TriPSs/conventional-changelog-action#264]
Required to have force push option, 
If we have main branch with protection rule that no one else can directly push to branch so force push can help there for allowing to push code from workflow actions

**Comment by rgoomar** [comment]
I'm also running into a similar problem where we can't setup branch protections without breaking the use of this action. Is there a way to circumvent that issue?

**Comment by TriPSs** [comment]
You can change the user that is used when committing, maybe add your own info/user there and configure that user to allow bypassing the checks.

There is also a medium post: https://medium.com/swlh/bump-bump-bump-d0dab616e83

**Comment by Simranpal-Bainee** [comment]
tried both, adding username, email of repo admin and also using token as mentioned in Medium post,
But still getting same error as:

``` ! [remote rejected] test -> test (protected branch hook declined) ```

**Comment by vinay-20** [comment]
I was able to fix this issue by also adding the token in the checkout step which is a precursor step in my case before using this action.

```
      - uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.USER_TOKEN }} # adding this fixed the issue.

      - name: Changelog
         uses: TriPSs/conventional-changelog-action@v5.3.0 # v5
```

P.S ; Along with the above change you will still have to setup new github user, create the PAT & provide neccessary permissions..
