### ISSUE TITLE
Error: Unable to load the "eslint" preset. Please make sure it's installed.

### ISSUE THREAD

**Issue by emma-ong-maker** [TriPSs/conventional-changelog-action#265]
Hi there, was wondering if anyone has encountered this and could shed some light on what I might be missing as a part of implementation? 

![image](https://github.com/TriPSs/conventional-changelog-action/assets/130513664/f3e18d4f-4146-40c4-844a-1bd6741cba7d)

When running as a github action, an error is thrown and it fails at this step given `preset` is set to `eslint`. 

Please note if there are NO issues if `preset` is set to `conventionalcommits`, and this action runs successfully. 

```
     # Bump version and push tag
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.3.0
        with:
          github-token: ${{ secrets.ENZ_ADMIN_TOKEN }}
          # https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint
          preset: 'eslint'
          output-file: 'CHANGELOG.md'
```

I have tried the following: 
1. Added the following prior to running the step `name: Conventional Changelog Action`, I have installed `eslint` and/or `conventional-changelog-eslint` as per [readme](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#install) under dev dependencies too
```
      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
          registry-url: 'https://registry.yarnpkg.com/' # Use Yarn registry

      # Install dependencies using Yarn
      - run: yarn install
```
2. Adding a `eslint.config.mjs` or `eslint.config.js` or .eslintrc.js`

Happy to provide more information if needed! Thank you
