### ISSUE TITLE
additional versions get updated instead of just one

### ISSUE THREAD

**Issue by dalbertom** [TriPSs/conventional-changelog-action#268]
Hi there,

I have a Helm chart where `Chart.yaml` looks something like this:

```
dependencies:
  - name: dependency-name
    version: "0.2.0"

version: 0.2.0
```

As you can see, the version is `0.2.0`, but the dependency happens to be on the same version, `"0.2.0"`. 

When I run the action with:
```
version-file: "Chart.yaml"
version-path: "version"
```

It ends up updating both entries rather than just the outer version. Is there a way to set `version-path` or use another option to leave the dependency version unchanged?

Thanks!
