### ISSUE TITLE
skip-ci = false doesn't trigger pipeline with on push tags v*

### ISSUE THREAD

**Issue by kachi-app** [TriPSs/conventional-changelog-action#276]
Configuration:
```
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          preset: "conventionalcommits"
          create-summary: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-on-empty: "false"
          skip-ci: 'false'
```
Here is the pipeline result
<img width="1663" alt="Image" src="https://github.com/user-attachments/assets/924e20ff-a414-41d1-ab35-a50e5ed31c5d" />

Release Commits
<img width="1107" alt="Image" src="https://github.com/user-attachments/assets/5a957b68-1316-40e0-829c-c2d61a66328c" />

Tags
<img width="959" alt="Image" src="https://github.com/user-attachments/assets/cbab4b5d-f71b-4527-9230-445dcfda00c2" />

Here is my other pipeline:
```
name: "[Release] Publish Packages"
on:
  push:
    tags:
      - 'v*'
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
```

However, after TriPSs/conventional-changelog-action push tags, I expect the pipeline should run

<img width="1575" alt="Image" src="https://github.com/user-attachments/assets/3a3a5a6d-abab-4f70-909a-cd93ace61813" />

Another issues is type: chore, ci, docs is not generated in the changelog. I am aware the preset issue. However based on https://www.conventionalcommits.org/en/v1.0.0/
`types other than fix: and feat: are allowed, for example [@commitlint/config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) (based on the [Angular convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines)) recommends build:, chore:, ci:, docs:, style:, refactor:, perf:, test:, and others`. Isn't it should works ? 

Thank you

**Comment by TriPSs** [comment]
I think this is something that GitHub itself does not do (anymore) from commits that are generated inside the CI, to prevent CI loops.

**Comment by kachi-app** [comment]
Hi @TriPSs , Thank you
I made it work with custom PAT
```

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          preset: "conventionalcommits"
          create-summary: true
          github-token: ${{ secrets.CHI_GITHUB_TOKEN }}
          skip-on-empty: "false"
          skip-ci: 'false'
```

Could you please help about the conventionalCommits ? it seems to me that only fix, and feat is working
