### ISSUE TITLE
Unable to obtain version

### ISSUE THREAD

**Issue by fingerart** [TriPSs/conventional-changelog-action#280]
I don't want to submit anything except the tag, get `version` from `package.json`, so my configuration is as follows:

```yml
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          version-file: "./package.json"
          create-summary: true
          output-file: false
          skip-commit: true
          skip-on-empty: true
          skip-bump: true

      - name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          append_body: true
          generate_release_notes: true
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
```

The following are the logs of key positions (where the v is empty):

```log
Using GIT to determine the new version

some changelog...

New version: 
/usr/bin/git tag -a v -m v
```

But I still can't get the version number in the `package.json` file correctly, which seems to be related to this:

https://github.com/TriPSs/conventional-changelog-action/blob/67139193614f5b9e8db87da1bd4240922b34d765/src/index.js#L125-L133
