### ISSUE TITLE
Make package.json optional

### ISSUE THREAD

**Issue by jcornaz** [TriPSs/conventional-changelog-action#32]
Hello, 

This action looks great!

However, I cannot help but notice that it wants a `package.json`. I saw we can choose where it is located.

But can we use this action when we don't have a `package.json` at all? Like for any project which is not based on `npm` (could be maven, gradle, cargo, elm, you name it)

**Comment by TriPSs** [comment]
Hi,

Technically speaking you should be able use any json file that looks like this:
```json
{
  "version": "1.0.0"
}
```

You could try the action like this:
```yaml
- name: Conventional Changelog Action
  uses: TriPSs/conventional-changelog-action@v2
  with:
    github-token: ${{ secrets.github_token }}
    package-json: './custom.json'
```

**Comment by jcornaz** [comment]
Thanks for the quick answer!

> Technically speaking you should be able use any json file that looks like this:

Well the tools I use don't rely on Json at all.

With [gradle](https://gradle.org/), my projects don't even have the version written anywhere. They relying solely on tags. (thanks to [reckon](https://github.com/ajoberstar/reckon))

And with [cargo](https://github.com/rust-lang/cargo/) the version is written in a [toml](https://github.com/toml-lang/toml) file like this

```toml
version = "1.0.0"
```

Of course there are plenty of other build tools with yet different ways of doing things. 

So I presume the answer is "no" I cannot use it for non-javascript projects?

On this basis I can reformulate my question into a feature request: "Make package.json"

**Comment by TriPSs** [comment]
Okay thanks for the explanation, so for Gradle it would be possible to just create a json file like described above? 

For cargo we can look into supporting the toml format, we could change `package-json` argument to `version-file` that will look into the file extension and based on that bumps the version in it accordingly.

**Comment by TriPSs** [comment]
Maybe also a nice addition would be the ability to define the path of the version, for example inside a json file the default will be `version` and the default for toml will be `package.version`, this way if the location of the version is on a different location you get the ability to change it.

**Comment by jcornaz** [comment]
> Gradle it would be possible to just create a json file like described above

Of  course I could always add an `echo "{ \"version\": \"0.0.0\" }" > package.json` step in my CI and delete after invoking `conventional-changelog-action` but I'd prefer to be able to configure the action with something like:


```yaml
- uses: TriPSs/conventional-changelog-action@v2
   with:
     github-token: ${{ secrets.github_token }}
     package-json: 'false'
```

> For cargo we can look into supporting the toml format

That would be awesome!
