### ISSUE TITLE
Error when merging pull request: pathspec did not match any file(s) known to git

### ISSUE THREAD

**Issue by ChannyAzar** [TriPSs/conventional-changelog-action#34]
Hi,

Thanks for this action!
I'm getting an error while merging my pull request into a branch.

```
name: Bump version
on:
  pull_request:
      branches: [ development, master-dev ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.github_token }}
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        git-message: 'chore(release): {version}'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
```

The error:

```
Run TriPSs/conventional-changelog-action@v2
Using "angular" preset
Using "chore(release): {version}" as commit message
Using "5" release count
Using "./package.json"
Using "v" as tag prefix
Using "CHANGELOG.md" as output file
Pull to make sure we have the full git history
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/my-repo.git
/usr/bin/git checkout refs/pull/14/merge
/usr/bin/git pull --unshallow
error: pathspec 'refs/pull/14/merge' did not match any file(s) known to git
(node:2489) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v2/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v2/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v2/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
```

**Comment by TriPSs** [comment]
Hi,

I think this has to do that the action is intended to run on a branch instead of a PR, like this:
```yaml
on:
  push:
    branches:
      - master
```
