### ISSUE TITLE
critical: `conventional-changelog-conventionalcommits` haven't installed in the 3.1.0 release

### ISSUE THREAD

**Issue by viktor-ku** [TriPSs/conventional-changelog-action#39]
### Issue

There it is for `3.0.0` [github.com/TriPSs/conventional-changelog-action/tree/v3.0.0/node_modules](https://github.com/TriPSs/conventional-changelog-action/tree/v3.0.0/node_modules)

And for `3.1.0` there is not [https://github.com/TriPSs/conventional-changelog-action/tree/v3.1.0/node_modules](https://github.com/TriPSs/conventional-changelog-action/tree/v3.1.0/node_modules)

For some very odd reason when I am using `yarn install` against `master` it does add `conventional-changelog-conventionalcommits` to the `node_modules`, but if I am using `yarn install --prod` it does not. 

I don't know what the hell it is, and how it is even possible, but it looks like when running release github action against 3.1.0 it run `yarn --production` and did not add `conventional-changelog-conventionalcommits` tot the node_modules.

It resulted in my workflow being now completely broken because I am using this action with `conventionalcommits` preset:

```yaml
      - name: Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): bump to {version}'
          preset: conventionalcommits
          pre-commit: ci/dist/index.js
          skip-on-empty: false
```

### Solution

Either

1. Use npm instead of yarn (with `npm ci` instead of `yarn --production` it is installing everything)
2. Use `yarn` without `--production`.
