### ISSUE TITLE
Add the generate changelog to the Github release

### ISSUE THREAD

**Issue by TriPSs** [TriPSs/conventional-changelog-action#6]
Make it possible to opt in to add the generated release to the tag in github releases

**Comment by Mateiadrielrafael** [comment]
any progress on this?

**Comment by TriPSs** [comment]
Hi @Mateiadrielrafael, I currently don't have time to work on this project but a PR is always welcome!

**Comment by Mateiadrielrafael** [comment]
Np, I was just curious

**Comment by TriPSs** [comment]
This is now possible with the latest release of this action in combination with [actions/create-release](https://github.com/actions/create-release). Example:

```
- name: Conventional Changelog Action
  id: changelog
  uses: TriPSs/conventional-changelog-action@v2
  with:
    github-token: ${{ secrets.github_token }}
    output-file: 'false'

- name: Create Release
  uses: actions/create-release@v1
  env:
   GITHUB_TOKEN: ${{ secrets.github_token }}
  with:
   tag_name: ${{ steps.changelog.outputs.tag }}
   release_name: ${{ steps.changelog.outputs.tag }}
   body: ${{ steps.changelog.outputs.clean_changelog }}
```
