### ISSUE TITLE
"/usr/bin/git' failed with exit code 128"

### ISSUE THREAD

**Issue by Kimba666** [TriPSs/conventional-changelog-action#60]
Action Fails with ~ 

`    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
(node:2675) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
Using "angular" preset
Using "chore(release): {version}" as commit message
Using "Conventional Changelog Action" as git user.name
Using "conventional.changelog.action@github.com" as git user.email
Using "5" release count
Using "./package.json" as version file
Using "version" as version path
Using "v" as tag prefix
Using "CHANGELOG.md" as output file
Using "" as config file
Skipping empty releases is "enabled"
Skipping the update of the version file is "disabled"
Pull to make sure we have the full git history
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/Kimba666/changelogs.git
/usr/bin/git pull --unshallow --tags --ff-only
fatal: not a git repository (or any of the parent directories): .git
fatal: not in a git directory
fatal: not in a git directory
fatal: not a git repository (or any of the parent directories): .git
##[error]The process '/usr/bin/git' failed with exit code 128`

**Comment by TriPSs** [comment]
Hi, the error states it's not a git repository, could you share some more info? Workflow for example.

**Comment by Kimba666** [comment]
Hello TriPSs! :D 

This is my first Github Action so I could just be configuring it wrong but~ 

`name: Conventional Changelog Action

on: [pull_request, push]
#
jobs:
  checkfiles:
    runs-on: ubuntu-latest
    steps:
    - uses: TriPSs/conventional-changelog-action@v3.4.0
      with:
        github-token: ${{ secrets.github_token }}`

This is my .yml that dictates how the action should function and I'm getting the error I listed above. Is there something I need to add and/or change in order to get a successful run?

**Comment by TriPSs** [comment]
A couple of points :)
1. You need the checkout step, this is needed to checkout the git repo
1. Personally i would not run this action on a PR or Push but on a merge to master like the example below
1. I would add `paths-ignore` to prevent the action running if only the `package.json` or `CHANGELOG.md` is changed, see example below.
```
name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}

```

Hopes this helps you.
