### ISSUE TITLE
Issue with git pull

### ISSUE THREAD

**Issue by asmyshlyaev177** [TriPSs/conventional-changelog-action#72]
Got this error.

```
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

Error: The process '/usr/bin/git' failed with exit code 1
```

It was run on PR.

Whole action file 
```
name: Version and changelog

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  version:
      name: version
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: TriPSs/conventional-changelog-action@v3
        with:
          push-branch: ${{ steps.extract_branch.outputs.branch }}
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          git-user-name: 'Awesome Changelog Action'
          git-user-email: 'awesome_changelog@github.actions.com'
          preset: 'angular'
          tag-prefix: 'v'
          release-count: '0'
```
