### ISSUE TITLE
silent error if tag already exists

### ISSUE THREAD

**Issue by stevie-** [TriPSs/conventional-changelog-action#74]
I think I've found a bug.

when the tag for next version already exists, there is an error, but workflow finished successfull.
Output of step:

```
#SNIPPET#
New version: 3.25.0
/usr/bin/git add .
/usr/bin/git commit -m chore(release): v3.25.0
[master f96c99e] chore(release): v3.25.0
 2 files changed, 28 insertions(+), 10 deletions(-)
/usr/bin/git tag -a v3.25.0 -m v3.25.0
fatal: tag 'v3.25.0' already exists
(node:2472) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/git' failed with exit code 128
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
(node:2472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:2472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Action settings
```
Run TriPSs/conventional-changelog-action@v3
  with:
    github-token: ***
    release-count: 20
    git-message: chore(release): {version}
    git-user-name: Conventional Changelog Action
    git-user-email: conventional.changelog.action@github.com
    git-pull-method: --ff-only
    preset: angular
    tag-prefix: v
    output-file: CHANGELOG.md
    version-file: ./package.json
    version-path: version
    skip-on-empty: true
    skip-version-file: false
    skip-commit: false
    fallback-version: 0.1.0
```
