### ISSUE TITLE
package.json not getting version update

### ISSUE THREAD

**Issue by ziccardi** [TriPSs/conventional-changelog-action#91]
Hello guys!
Any clue why `TriPSs/conventional-changelog-action@v3` is updating the version only inside the `package-lock.json` and is ignoring the `package.json` file?

Below my workflow definition:

```yaml
name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTION_TOKEN }}
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.ACTION_TOKEN }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: ''
        output-file: 'CHANGELOG.md'
        skip-on-empty: true
        version-file: 'package.json, package-lock.json'
```
