### ISSUE TITLE
Skip creating tag

### ISSUE THREAD

**Issue by kamronbatman** [TriPSs/conventional-changelog-action#97]
I use this action for the body that it produces, but I don't use the versioning or other features.
I would love the ability to skip creating the tag itself since it is duplicative (and in my case, the wrong version).

**Comment by TriPSs** [comment]
Hi, currently the tag is required to determine the changes. I was thinking of a addition to put your config for this action inside for example `.changelog-action` file where beside the config the version and it's git sha could be stored, but until then creating a git tag is required.

**Comment by kamronbatman** [comment]
Yeah that would be great. An output variable, or file is good enough and should allow for skipping the tag without problem.

**Comment by datapolitical** [comment]
I’m having the same issue. I have a precious step that increments the version, and so I just want this to generate the changelog text.

it looks like you have a feature for allowing a script to generate the tag, it would be nice if there was just a way to just specify it (so I could get it from the output of another step).

is there a way to hack that option “pre-changelog-generation” so as to just hand it a variable like “steps.version_updater.outputs.newversion”?

**Comment by TriPSs** [comment]
@datapolitical that should be possible, if you pass the new version as env variable to the action it should be available inside the script.

**Comment by datapolitical** [comment]
Yeah but how do you tell the action to use the environment variable?

**Comment by TriPSs** [comment]
@datapolitical something like this (see the env): 
```
- name: Conventional Changelog Action
  id: changelog
  uses: TriPSs/conventional-changelog-action@v3
  with:
    github-token: ${{ secrets.github_token }}
  env:
    NEW_VERSION: ${{ steps.version_updater.outputs.newversion }}
```
